Workflow dependencies functioning

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,5 +30,5 @@ jobs:
       - name: Run Tests
         run: ./run_tests.sh
 
-      - name: Test Deploy Workflow Dependency on Failure
-        run: exit 1
+      # - name: Test Deploy Workflow Dependency on Failure
+      #   run: exit 1
